import { Inter } from "next/font/google";
import "../../public/assets/style/globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { ReduxProvider } from "./providers/providers";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ReduxProvider>
        {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
